import { MedicationShape } from '../models';

export interface MedicationCatalogItem {
  id: string;
  name: string;
  active_ingredient: string;
  dosage_text: string;
  usage_note: string;
  shape: MedicationShape;
  color: string;
  category: string;
  icon: string;
}

export const medicationCategoryOptions = [
  { label: 'Agri / Ates', value: 'pain_fever', icon: 'thermometer-outline' },
  { label: 'Antibiyotik', value: 'antibiotic', icon: 'bug-outline' },
  { label: 'Alerji / Solunum', value: 'allergy_resp', icon: 'leaf-outline' },
  { label: 'Kalp / Tansiyon', value: 'heart_pressure', icon: 'heart-outline' },
  { label: 'Diyabet', value: 'diabetes', icon: 'water-outline' },
  { label: 'Hormon / Tiroid', value: 'hormone', icon: 'pulse-outline' },
  { label: 'Mide', value: 'stomach', icon: 'restaurant-outline' },
  { label: 'Krem / Damla', value: 'skin_drops', icon: 'color-fill-outline' },
  { label: 'Vitamin', value: 'vitamin', icon: 'sparkles-outline' },
  { label: 'Diger', value: 'other', icon: 'cube-outline' },
];

export const dosagePresetOptions = [
  { label: '250 mg', value: '250 mg' },
  { label: '400 mg', value: '400 mg' },
  { label: '500 mg', value: '500 mg' },
  { label: '1000 mg', value: '1000 mg' },
  { label: '5 ml', value: '5 ml' },
  { label: '10 ml', value: '10 ml' },
  { label: '1 tablet', value: '1 tablet' },
  { label: '1 kapsul', value: '1 kapsul' },
  { label: '1 damla', value: '1 damla' },
  { label: '1 doz', value: '1 doz' },
  { label: 'Doktorun belirttigi doz', value: 'Doktorun belirttigi doz' },
];

export const usageInstructionOptions = [
  { label: 'Yemekle bagimsiz', value: 'Yemekle bagimsiz' },
  { label: 'Ac karnina', value: 'Ac karnina' },
  { label: 'Yemekten sonra', value: 'Yemekten sonra' },
  { label: 'Yemekten once', value: 'Yemekten once' },
  { label: 'Bol su ile', value: 'Bol su ile' },
  { label: 'Doktorun belirttigi sekilde', value: 'Doktorun belirttigi sekilde' },
  { label: 'Gerektiginde kullan', value: 'Gerektiginde kullan' },
  { label: 'Gece kullan', value: 'Gece kullan' },
];

export const notifyBeforeOptions = [
  { label: 'Tam saatinde', value: '0' },
  { label: '5 dk once', value: '5' },
  { label: '10 dk once', value: '10' },
  { label: '15 dk once', value: '15' },
  { label: '30 dk once', value: '30' },
  { label: '1 saat once', value: '60' },
];

export const medicationCatalog: MedicationCatalogItem[] = [
  {
    id: 'paracetamol-tablet',
    name: 'Parasetamol',
    active_ingredient: 'Parasetamol',
    dosage_text: '500 mg',
    usage_note: 'Doktorun belirttigi sekilde',
    shape: MedicationShape.TABLET,
    color: '#4A90E2',
    category: 'pain_fever',
    icon: 'thermometer-outline',
  },
  {
    id: 'minoset-tablet',
    name: 'Minoset',
    active_ingredient: 'Parasetamol',
    dosage_text: '500 mg',
    usage_note: 'Gerektiginde kullan',
    shape: MedicationShape.TABLET,
    color: '#4A90E2',
    category: 'pain_fever',
    icon: 'thermometer-outline',
  },
  {
    id: 'calpol-drops',
    name: 'Calpol',
    active_ingredient: 'Parasetamol',
    dosage_text: 'Doktorun belirttigi doz',
    usage_note: 'Doktorun belirttigi sekilde',
    shape: MedicationShape.DROPS,
    color: '#4A90E2',
    category: 'pain_fever',
    icon: 'thermometer-outline',
  },
  {
    id: 'ibuprofen-tablet',
    name: 'Ibuprofen',
    active_ingredient: 'Ibuprofen',
    dosage_text: '400 mg',
    usage_note: 'Yemekten sonra',
    shape: MedicationShape.TABLET,
    color: '#F59E0B',
    category: 'pain_fever',
    icon: 'thermometer-outline',
  },
  {
    id: 'nurofen-tablet',
    name: 'Nurofen',
    active_ingredient: 'Ibuprofen',
    dosage_text: '400 mg',
    usage_note: 'Yemekten sonra',
    shape: MedicationShape.TABLET,
    color: '#F59E0B',
    category: 'pain_fever',
    icon: 'thermometer-outline',
  },
  {
    id: 'naproxen-tablet',
    name: 'Naproksen',
    active_ingredient: 'Naproksen',
    dosage_text: '500 mg',
    usage_note: 'Yemekten sonra',
    shape: MedicationShape.TABLET,
    color: '#F97316',
    category: 'pain_fever',
    icon: 'thermometer-outline',
  },
  {
    id: 'apranax-tablet',
    name: 'Apranax',
    active_ingredient: 'Naproksen sodyum',
    dosage_text: '550 mg',
    usage_note: 'Yemekten sonra',
    shape: MedicationShape.TABLET,
    color: '#F97316',
    category: 'pain_fever',
    icon: 'thermometer-outline',
  },
  {
    id: 'arveles-tablet',
    name: 'Arveles',
    active_ingredient: 'Deksketoprofen',
    dosage_text: '25 mg',
    usage_note: 'Yemekten sonra',
    shape: MedicationShape.TABLET,
    color: '#F59E0B',
    category: 'pain_fever',
    icon: 'thermometer-outline',
  },
  {
    id: 'diclofenac-tablet',
    name: 'Diklofenak',
    active_ingredient: 'Diklofenak',
    dosage_text: '50 mg',
    usage_note: 'Yemekten sonra',
    shape: MedicationShape.TABLET,
    color: '#F59E0B',
    category: 'pain_fever',
    icon: 'thermometer-outline',
  },
  {
    id: 'majezik-tablet',
    name: 'Majezik',
    active_ingredient: 'Flurbiprofen',
    dosage_text: '100 mg',
    usage_note: 'Yemekten sonra',
    shape: MedicationShape.TABLET,
    color: '#F97316',
    category: 'pain_fever',
    icon: 'thermometer-outline',
  },

  {
    id: 'amoxicillin-capsule',
    name: 'Amoksisilin',
    active_ingredient: 'Amoksisilin',
    dosage_text: '500 mg',
    usage_note: 'Doktorun belirttigi sekilde',
    shape: MedicationShape.CAPSULE,
    color: '#E5484D',
    category: 'antibiotic',
    icon: 'bug-outline',
  },
  {
    id: 'augmentin-tablet',
    name: 'Augmentin',
    active_ingredient: 'Amoksisilin + Klavulanik Asit',
    dosage_text: '1000 mg',
    usage_note: 'Yemekten sonra',
    shape: MedicationShape.TABLET,
    color: '#E5484D',
    category: 'antibiotic',
    icon: 'bug-outline',
  },
  {
    id: 'azithromycin-tablet',
    name: 'Azitromisin',
    active_ingredient: 'Azitromisin',
    dosage_text: '500 mg',
    usage_note: 'Doktorun belirttigi sekilde',
    shape: MedicationShape.TABLET,
    color: '#E5484D',
    category: 'antibiotic',
    icon: 'bug-outline',
  },
  {
    id: 'klacid-tablet',
    name: 'Klacid',
    active_ingredient: 'Klaritromisin',
    dosage_text: '500 mg',
    usage_note: 'Doktorun belirttigi sekilde',
    shape: MedicationShape.TABLET,
    color: '#E5484D',
    category: 'antibiotic',
    icon: 'bug-outline',
  },
  {
    id: 'cefuroxime-tablet',
    name: 'Sefuroksim',
    active_ingredient: 'Sefuroksim',
    dosage_text: '500 mg',
    usage_note: 'Doktorun belirttigi sekilde',
    shape: MedicationShape.TABLET,
    color: '#E5484D',
    category: 'antibiotic',
    icon: 'bug-outline',
  },
  {
    id: 'cipro-tablet',
    name: 'Cipro',
    active_ingredient: 'Siprofloksasin',
    dosage_text: '500 mg',
    usage_note: 'Doktorun belirttigi sekilde',
    shape: MedicationShape.TABLET,
    color: '#E5484D',
    category: 'antibiotic',
    icon: 'bug-outline',
  },
  {
    id: 'flagyl-tablet',
    name: 'Flagyl',
    active_ingredient: 'Metronidazol',
    dosage_text: '500 mg',
    usage_note: 'Doktorun belirttigi sekilde',
    shape: MedicationShape.TABLET,
    color: '#E5484D',
    category: 'antibiotic',
    icon: 'bug-outline',
  },
  {
    id: 'monodoks-capsule',
    name: 'Monodoks',
    active_ingredient: 'Doksisiklin',
    dosage_text: '100 mg',
    usage_note: 'Bol su ile',
    shape: MedicationShape.CAPSULE,
    color: '#E5484D',
    category: 'antibiotic',
    icon: 'bug-outline',
  },

  {
    id: 'cetirizine-tablet',
    name: 'Setirizin',
    active_ingredient: 'Setirizin',
    dosage_text: '10 mg',
    usage_note: 'Gece kullan',
    shape: MedicationShape.TABLET,
    color: '#10B981',
    category: 'allergy_resp',
    icon: 'leaf-outline',
  },
  {
    id: 'loratadine-tablet',
    name: 'Loratadin',
    active_ingredient: 'Loratadin',
    dosage_text: '10 mg',
    usage_note: 'Yemekle bagimsiz',
    shape: MedicationShape.TABLET,
    color: '#10B981',
    category: 'allergy_resp',
    icon: 'leaf-outline',
  },
  {
    id: 'desloratadine-tablet',
    name: 'Desloratadin',
    active_ingredient: 'Desloratadin',
    dosage_text: '5 mg',
    usage_note: 'Yemekle bagimsiz',
    shape: MedicationShape.TABLET,
    color: '#10B981',
    category: 'allergy_resp',
    icon: 'leaf-outline',
  },
  {
    id: 'aerius-tablet',
    name: 'Aerius',
    active_ingredient: 'Desloratadin',
    dosage_text: '5 mg',
    usage_note: 'Yemekle bagimsiz',
    shape: MedicationShape.TABLET,
    color: '#10B981',
    category: 'allergy_resp',
    icon: 'leaf-outline',
  },
  {
    id: 'montelukast-tablet',
    name: 'Montelukast',
    active_ingredient: 'Montelukast',
    dosage_text: '10 mg',
    usage_note: 'Gece kullan',
    shape: MedicationShape.TABLET,
    color: '#10B981',
    category: 'allergy_resp',
    icon: 'leaf-outline',
  },
  {
    id: 'salbutamol-inhaler',
    name: 'Salbutamol',
    active_ingredient: 'Salbutamol',
    dosage_text: '1 doz',
    usage_note: 'Gerektiginde kullan',
    shape: MedicationShape.DROPS,
    color: '#0EA5E9',
    category: 'allergy_resp',
    icon: 'fitness-outline',
  },
  {
    id: 'ventolin-inhaler',
    name: 'Ventolin',
    active_ingredient: 'Salbutamol',
    dosage_text: '1 doz',
    usage_note: 'Gerektiginde kullan',
    shape: MedicationShape.DROPS,
    color: '#0EA5E9',
    category: 'allergy_resp',
    icon: 'fitness-outline',
  },

  {
    id: 'amlodipine-tablet',
    name: 'Amlodipin',
    active_ingredient: 'Amlodipin',
    dosage_text: '5 mg',
    usage_note: 'Doktorun belirttigi sekilde',
    shape: MedicationShape.TABLET,
    color: '#8B5CF6',
    category: 'heart_pressure',
    icon: 'heart-outline',
  },
  {
    id: 'metoprolol-tablet',
    name: 'Metoprolol',
    active_ingredient: 'Metoprolol',
    dosage_text: '50 mg',
    usage_note: 'Doktorun belirttigi sekilde',
    shape: MedicationShape.TABLET,
    color: '#8B5CF6',
    category: 'heart_pressure',
    icon: 'heart-outline',
  },
  {
    id: 'beloc-tablet',
    name: 'Beloc',
    active_ingredient: 'Metoprolol',
    dosage_text: '50 mg',
    usage_note: 'Doktorun belirttigi sekilde',
    shape: MedicationShape.TABLET,
    color: '#8B5CF6',
    category: 'heart_pressure',
    icon: 'heart-outline',
  },
  {
    id: 'acetylsalicylic-tablet',
    name: 'Asetilsalisilik asit',
    active_ingredient: 'Asetilsalisilik asit',
    dosage_text: '100 mg',
    usage_note: 'Doktorun belirttigi sekilde',
    shape: MedicationShape.TABLET,
    color: '#64748B',
    category: 'heart_pressure',
    icon: 'heart-outline',
  },
  {
    id: 'coraspin-tablet',
    name: 'Coraspin',
    active_ingredient: 'Asetilsalisilik asit',
    dosage_text: '100 mg',
    usage_note: 'Doktorun belirttigi sekilde',
    shape: MedicationShape.TABLET,
    color: '#64748B',
    category: 'heart_pressure',
    icon: 'heart-outline',
  },
  {
    id: 'valsartan-tablet',
    name: 'Valsartan',
    active_ingredient: 'Valsartan',
    dosage_text: '80 mg',
    usage_note: 'Doktorun belirttigi sekilde',
    shape: MedicationShape.TABLET,
    color: '#8B5CF6',
    category: 'heart_pressure',
    icon: 'heart-outline',
  },
  {
    id: 'losartan-tablet',
    name: 'Losartan',
    active_ingredient: 'Losartan',
    dosage_text: '50 mg',
    usage_note: 'Doktorun belirttigi sekilde',
    shape: MedicationShape.TABLET,
    color: '#8B5CF6',
    category: 'heart_pressure',
    icon: 'heart-outline',
  },
  {
    id: 'enapril-tablet',
    name: 'Enalapril',
    active_ingredient: 'Enalapril',
    dosage_text: '10 mg',
    usage_note: 'Doktorun belirttigi sekilde',
    shape: MedicationShape.TABLET,
    color: '#8B5CF6',
    category: 'heart_pressure',
    icon: 'heart-outline',
  },

  {
    id: 'metformin-tablet',
    name: 'Metformin',
    active_ingredient: 'Metformin',
    dosage_text: '500 mg',
    usage_note: 'Yemekten sonra',
    shape: MedicationShape.TABLET,
    color: '#0EA5E9',
    category: 'diabetes',
    icon: 'water-outline',
  },
  {
    id: 'glifor-tablet',
    name: 'Glifor',
    active_ingredient: 'Metformin',
    dosage_text: '1000 mg',
    usage_note: 'Yemekten sonra',
    shape: MedicationShape.TABLET,
    color: '#0EA5E9',
    category: 'diabetes',
    icon: 'water-outline',
  },
  {
    id: 'glucophage-tablet',
    name: 'Glucophage',
    active_ingredient: 'Metformin',
    dosage_text: '1000 mg',
    usage_note: 'Yemekten sonra',
    shape: MedicationShape.TABLET,
    color: '#0EA5E9',
    category: 'diabetes',
    icon: 'water-outline',
  },
  {
    id: 'insulin-pen',
    name: 'Insulin',
    active_ingredient: 'Insulin',
    dosage_text: 'Doktorun belirttigi doz',
    usage_note: 'Doktorun belirttigi sekilde',
    shape: MedicationShape.INJECTION,
    color: '#0EA5E9',
    category: 'diabetes',
    icon: 'fitness-outline',
  },
  {
    id: 'januvia-tablet',
    name: 'Januvia',
    active_ingredient: 'Sitagliptin',
    dosage_text: '100 mg',
    usage_note: 'Doktorun belirttigi sekilde',
    shape: MedicationShape.TABLET,
    color: '#0EA5E9',
    category: 'diabetes',
    icon: 'water-outline',
  },

  {
    id: 'levothyroxine-tablet',
    name: 'Levotiroksin',
    active_ingredient: 'Levotiroksin',
    dosage_text: '50 mcg',
    usage_note: 'Ac karnina',
    shape: MedicationShape.TABLET,
    color: '#EC4899',
    category: 'hormone',
    icon: 'pulse-outline',
  },
  {
    id: 'euthyrox-tablet',
    name: 'Euthyrox',
    active_ingredient: 'Levotiroksin',
    dosage_text: '50 mcg',
    usage_note: 'Ac karnina',
    shape: MedicationShape.TABLET,
    color: '#EC4899',
    category: 'hormone',
    icon: 'pulse-outline',
  },
  {
    id: 'tefor-tablet',
    name: 'Tefor',
    active_ingredient: 'Levotiroksin',
    dosage_text: '50 mcg',
    usage_note: 'Ac karnina',
    shape: MedicationShape.TABLET,
    color: '#EC4899',
    category: 'hormone',
    icon: 'pulse-outline',
  },

  {
    id: 'omeprazole-capsule',
    name: 'Omeprazol',
    active_ingredient: 'Omeprazol',
    dosage_text: '20 mg',
    usage_note: 'Yemekten once',
    shape: MedicationShape.CAPSULE,
    color: '#F97316',
    category: 'stomach',
    icon: 'restaurant-outline',
  },
  {
    id: 'pantoprazole-tablet',
    name: 'Pantoprazol',
    active_ingredient: 'Pantoprazol',
    dosage_text: '40 mg',
    usage_note: 'Yemekten once',
    shape: MedicationShape.TABLET,
    color: '#F97316',
    category: 'stomach',
    icon: 'restaurant-outline',
  },
  {
    id: 'lansor-capsule',
    name: 'Lansor',
    active_ingredient: 'Lansoprazol',
    dosage_text: '30 mg',
    usage_note: 'Yemekten once',
    shape: MedicationShape.CAPSULE,
    color: '#F97316',
    category: 'stomach',
    icon: 'restaurant-outline',
  },
  {
    id: 'nexium-tablet',
    name: 'Nexium',
    active_ingredient: 'Esomeprazol',
    dosage_text: '40 mg',
    usage_note: 'Yemekten once',
    shape: MedicationShape.TABLET,
    color: '#F97316',
    category: 'stomach',
    icon: 'restaurant-outline',
  },
  {
    id: 'gaviscon-liquid',
    name: 'Gaviscon',
    active_ingredient: 'Sodyum Aljinat',
    dosage_text: '10 ml',
    usage_note: 'Yemekten sonra',
    shape: MedicationShape.DROPS,
    color: '#F97316',
    category: 'stomach',
    icon: 'restaurant-outline',
  },
  {
    id: 'rennie-tablet',
    name: 'Rennie',
    active_ingredient: 'Kalsiyum karbonat + Magnezyum karbonat',
    dosage_text: '1 tablet',
    usage_note: 'Gerektiginde kullan',
    shape: MedicationShape.TABLET,
    color: '#F97316',
    category: 'stomach',
    icon: 'restaurant-outline',
  },

  {
    id: 'vitamin-d-drops',
    name: 'D vitamini',
    active_ingredient: 'Kolekalsiferol',
    dosage_text: '1 damla',
    usage_note: 'Doktorun belirttigi sekilde',
    shape: MedicationShape.DROPS,
    color: '#F59E0B',
    category: 'vitamin',
    icon: 'sparkles-outline',
  },
  {
    id: 'iron-tablet',
    name: 'Demir',
    active_ingredient: 'Demir',
    dosage_text: '1 tablet',
    usage_note: 'Doktorun belirttigi sekilde',
    shape: MedicationShape.TABLET,
    color: '#64748B',
    category: 'vitamin',
    icon: 'sparkles-outline',
  },
  {
    id: 'bemiks-tablet',
    name: 'Bemiks C',
    active_ingredient: 'B vitamini kompleksi',
    dosage_text: '1 tablet',
    usage_note: 'Yemekten sonra',
    shape: MedicationShape.TABLET,
    color: '#F59E0B',
    category: 'vitamin',
    icon: 'sparkles-outline',
  },
  {
    id: 'supradyn-tablet',
    name: 'Supradyn',
    active_ingredient: 'Multivitamin',
    dosage_text: '1 tablet',
    usage_note: 'Yemekten sonra',
    shape: MedicationShape.TABLET,
    color: '#F59E0B',
    category: 'vitamin',
    icon: 'sparkles-outline',
  },
  {
    id: 'magnesium-tablet',
    name: 'Magnezyum',
    active_ingredient: 'Magnezyum',
    dosage_text: '1 tablet',
    usage_note: 'Yemekten sonra',
    shape: MedicationShape.TABLET,
    color: '#F59E0B',
    category: 'vitamin',
    icon: 'sparkles-outline',
  },
  {
    id: 'omega3-capsule',
    name: 'Omega 3',
    active_ingredient: 'Balik yagi',
    dosage_text: '1 kapsul',
    usage_note: 'Yemekten sonra',
    shape: MedicationShape.CAPSULE,
    color: '#F59E0B',
    category: 'vitamin',
    icon: 'sparkles-outline',
  },

  {
    id: 'eye-drop',
    name: 'Goz damlasi',
    active_ingredient: 'Doktorun belirttigi etken madde',
    dosage_text: '1 damla',
    usage_note: 'Doktorun belirttigi sekilde',
    shape: MedicationShape.DROPS,
    color: '#10B981',
    category: 'skin_drops',
    icon: 'eye-outline',
  },
  {
    id: 'artificial-tear-drop',
    name: 'Suni gozyasi',
    active_ingredient: 'Sodyum hiyaluronat',
    dosage_text: '1 damla',
    usage_note: 'Gerektiginde kullan',
    shape: MedicationShape.DROPS,
    color: '#10B981',
    category: 'skin_drops',
    icon: 'eye-outline',
  },
  {
    id: 'skin-cream',
    name: 'Cilt kremi',
    active_ingredient: 'Doktorun belirttigi etken madde',
    dosage_text: '1 doz',
    usage_note: 'Doktorun belirttigi sekilde',
    shape: MedicationShape.CREAM,
    color: '#EC4899',
    category: 'skin_drops',
    icon: 'color-fill-outline',
  },
  {
    id: 'fucidin-cream',
    name: 'Fucidin',
    active_ingredient: 'Fusidik asit',
    dosage_text: '1 doz',
    usage_note: 'Doktorun belirttigi sekilde',
    shape: MedicationShape.CREAM,
    color: '#EC4899',
    category: 'skin_drops',
    icon: 'color-fill-outline',
  },
  {
    id: 'bepanthol-cream',
    name: 'Bepanthol',
    active_ingredient: 'Dekspantenol',
    dosage_text: '1 doz',
    usage_note: 'Gerektiginde kullan',
    shape: MedicationShape.CREAM,
    color: '#EC4899',
    category: 'skin_drops',
    icon: 'color-fill-outline',
  },

  {
    id: 'cold-flu-tablet',
    name: 'Aferin',
    active_ingredient: 'Parasetamol + Klorfeniramin',
    dosage_text: '1 tablet',
    usage_note: 'Doktorun belirttigi sekilde',
    shape: MedicationShape.TABLET,
    color: '#64748B',
    category: 'other',
    icon: 'cube-outline',
  },
  {
    id: 'theraflu-tablet',
    name: 'Theraflu',
    active_ingredient: 'Parasetamol kombinasyonu',
    dosage_text: '1 tablet',
    usage_note: 'Doktorun belirttigi sekilde',
    shape: MedicationShape.TABLET,
    color: '#64748B',
    category: 'other',
    icon: 'cube-outline',
  },
];

export const getMedicationCategoryLabel = (value?: string) =>
  medicationCategoryOptions.find((item) => item.value === value)?.label || '📦 Diger';